config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :players
  resources :tags

end

app/models/player.rb
class Player < ActiveRecord::Base

has_and_belongs_to_many :tags

end

app/models/players_tags.rb
class PlayersTags < ActiveRecord::Base
  belongs_to :player
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :players

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @player = Player.all
  end

  def new
    @player = Player.new
    @tags = Tag.all
  end


  def create

    # render :json => params
    @player = Player.create(player_params)
    tags = params[:player][:tags]
    tags.each do |tag_id|
      @player.tags << Tag.find_by_id(tag_id) unless tag_id.blank?
    end
    if @player.save
      redirect_to players_path
    else
      render 'new'
    end
  end

    FlickRaw.api_key=ENV['API_KEY']
    FlickRaw.shared_secret=ENV['API_SECRET']
  def show
    @player = Player.find(params[:id])
    @tags = @player.tags
    @photos= flickr.photos.search(:text => "#{@player["name"]} baseball",:per_page => 1,:tagged =>  "#{@player["team"]}", :sort => "relevance")
    # render :json => @photos
  end

  def edit
    @player = Player.find(params[:id])
    @tags = Tag.all
  end

  def update
    # render :json => params
    @player = Player.find(params[:id])
    @player.tags.clear
    tags = params[:player][:tag_ids]
    tags.each do |tag_id|
      @player.tags << Tag.find(tag_id) unless tag_id.blank?
    end

    if @player.update(player_params)
      redirect_to players_path
    else
      render 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:name,:team,:position)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def show
     @tag = Tag.find(params[:id])
     player_ids= PlayersTags.where(tag_id:@tag)
     @players = []
     player_ids.each do |p|
        @players << Player.find(p.player_id)
      end
     # render :json => @players
  end


  def create
    @tag = Tag.create(tag_params)
    if @tag.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def destroy
    # render :json => params
    @tag = Tag.find(params[:id])
    @times = PlayersTags.where(tag_id:@tag).length
    if PlayersTags.find_by_tag_id(@tag)
      if @times > 1
        flash[:danger] = "Sorry, this tag is in use: #{@times} times"
      else
        flash[:danger] = "Sorry, this tag is in use: #{@times} time"
      end
      redirect_to tags_path
    else
      @tag.destroy
      redirect_to tags_path
    end

  end


  private

  def tag_params
    params.require(:tag).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='text-center title-div'>

  <h1><%= link_to 'Baseball Card Collector', players_path, :class => 'title' %></h1>
  <h3>Create, Tag, and Collect all the players you want!</h3>
  <!-- <img class='image-collage' src="http://4.bp.blogspot.com/-5ryhAW4Ct0Y/Ux-qzvPZhmI/AAAAAAAAIy0/SoYLPesJHUc/s1600/P1140832.JPG"> -->
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |k,v| %>
  <div class='alert alert-<%= k %> col-md-4 col-md-offset-4 text-center'>
    <%= v %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Card Creator</title>
  <link href='http://fonts.googleeapis.com/css?family=Merriweather,400italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS & JS -->
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
  <a class="navbar-brand" href="/">Home</a>
  <ul class="nav navbar-nav">
    <li class="active">
      <a href="/players/">Cards</a>
    </li>
    <li class="active">
      <a href="/tags/">Tags</a>
    </li>
  </ul>
</nav>
<div class='blend'>
<div class= 'row'>
  <%= render 'layouts/flash' %>
</div>
  <div class='container'>


<%= yield %>


  </div>
  </div>
</body>
</html>

app/views/players/edit.html.erb
<h1>Edit Player</h1>

<div class='col-md-4 col-md-offset-4'>
<%= bootstrap_form_for (@player) do |f| %>

  <%= f.text_field :name, placeholder: "Player's Name" %>

  <%= f.text_field :team, placeholder: "Player's Current Team" %>

  <%= f.text_field :position, placeholder: "Player's Position" %>
  <%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
  <%= f.submit 'Submit', :class => 'btn btn-primary text-center' %>
<% end %>

</div>

app/views/players/index.html.erb
<div class='row'>
</div>
<div class='row'>
  <div class='col-md-4 col-md-offset-4'>
    <table class='player-index-table'>
        <tr>
          <td class='text-center'>
            <h1 class='player-index-list-title'>Created Cards</h1>
          </td>
         <tr>
          <td class='text-center create-card-btn-div'>
            <a href='/players/new' class='btn btn-primary btn-xs' style='margin: auto'>Create New Card</a>


          </td>
        </tr>
        </tr>
          <tr>
            <td>
            <ul>
              <% @player.each do |p| %>
              <li class='player-index-li'><%= link_to p.name, p %></li>
              <% end %>
            </ul>
            </td>

          </tr>
    </table>
  </div>
</div>

app/views/players/new.html.erb
<h1 class='text-center new-card-title'>Create a New Card</h1>

<div class='col-md-4 col-md-offset-4'>
<%= bootstrap_form_for (@player) do |f| %>

  <%= f.text_field :name, placeholder: "Player's Name" %>

  <%= f.text_field :team, placeholder: "Player's Team" %>

  <%= f.text_field :position, placeholder: "Player's Position" %>

  <%= f.collection_check_boxes :tags, @tags, :id, :name %>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/players/show.html.erb
<div class='row'>
<div class='col-md-4 col-md-offset-4'>
<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
  <div class="flipper">
    <div class="front">
      <table class='card-table'>
      <tr>
      <td>
        <h1 class='card-name'><%= @player.name %></h1>
        <% @photos.each do |photo| %>

        <div>
          <img src="<%= "http://farm#{photo['farm']}.staticflickr.com/#{photo["server"]}/#{photo["id"]}_#{photo["secret"]}.jpg" %>" class='player-image'>
        </div>
        <% end %>
        <div class='text-center player-team-position'>
          <%= @player.team %>
          <%= @player.position %>
        </div>
      </td>
      </tr>
      </table>
    </div>
    <div class="back">
      <table class='card-table-back'>
      <tr>
      <td>
        <h1 class='card-name-back'><%= @player.name %></h1>
        <table class='stat-table-inner'>
        <tr>
          <td>
            <h2 class='text-center stat-table-inner-title'>Tags</h2>

          </td>
        </tr>
        <tr>
        <td>
          <ul class='player-tag-list'>
            <% @tags.each do |tag| %>

              <li class='stat-tag'><%= link_to tag.name, tag_path(tag.id) %></li>
            <% end %>
          </ul>
         </td>
         </tr>
         <tr>
         <td>
        <div class='row  text-center'>
  <%= link_to '', edit_player_path, :class =>'btn btn-primary btn-xs glyphicon glyphicon-pencil' %>
  <%= link_to '', player_path, :class =>'btn btn-danger btn-xs glyphicon glyphicon-trash danger',
        method: :delete,
        data: {confirm: 'Are you sure?'} %>
</div>
        </td>
        </tr>
        </table>
      </table>
    </div>
  </div>
</div>
</div>

</div>

app/views/tags/index.html.erb
<div class='row'>
  <table class='col-md-4 col-md-offset-4 tag-index-table'>
    <tr>
      <td class='tag-index-title-width text-center'>
        <h1 class='tag-index-title'>Created Tags</h1>
      </td>
    </tr>
    <tr>
      <td>

        <div class='row text-center create-new-tag-btn'>
          <%= link_to 'Create New Tag', new_tag_path, :class => 'btn btn-primary btn-xs' %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
      <ul>
    <% @tags.each do |tag| %>
        <li class='created-tag-list-item'><%= link_to tag.name, tag_path(tag.id), :class => 'tag-index-link ' %>
        <%= link_to '', tag_path(tag.id), :class =>'btn btn-danger btn-xs glyphicon glyphicon-trash danger pull-right',
              method: :delete,
              data: {confirm: 'Are you sure?'} %></li>
    <% end %>
        </ul>
      </td>
    </tr>
  </table>
</div>

app/views/tags/new.html.erb
<div class='row'>
  <h1 class='text-center new-tag-title'>Create a New Tag</h1>
</div>
<div class='row col-md-4 col-md-offset-4'>
  <%= bootstrap_form_for @tag do |f| %>
    <%= f.text_field :name, placeholder: 'Enter the new tag' %>
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/tags/show.html.erb
<div class='row'>
  <div class='col-md-4 col-md-offset-4'>
    <table class='tag-show-table-list'>
      <tr>
        <td>
          <h1 class='text-center'><%= @tag.name %></h1>
        </td>
      </tr>
      <tr>
        <td>
          <ul>
        <% @players.each do |p| %>
            <li><%= link_to p.name, player_path(p.id) %></li>
        <% end %>
          </ul>
        </td>
      </tr>
    </table>
  </div>
</div>